[package]
name = "faucet"
version = "0.2.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[dependencies]
log = "0.4.6"
env_logger = "0.6.1"
clap = "3.0.0-beta.2"
chrono = "0.4.19"
tokio = { version = "0.2.22", features = ["full"] }
runtime = { path = "../runtime" }
bitcoin = { path = "../bitcoin", features = ["cli"] }
thiserror = "1.0"
jsonrpc-http-server = "16.0.0"
jsonrpsee = "0.1.0"
parity-scale-codec = "1.3.1"
serde_json = "1.0.57"
sp-core = "2.0.0"
sp-keyring = "2.0.0"
serde = "1.0.116"
futures = "0.3.5"
hex = "0.4.2"
kv = { version = "0.22.0", features = ["json-value"] }

[dev-dependencies.btc-parachain]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.3.2"

[dev-dependencies]
substrate-subxt-client = "0.4.0"
tempdir = "0.3.7"
sp-keyring = "2.0.0"