[package]
name = "faucet"
version = "0.2.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[dependencies]
log = "0.4.6"
env_logger = "0.6.1"
clap = "3.0.0-beta.2"
chrono = "0.4.19"
tokio = { version = "0.2.22", features = ["full"] }
runtime = { path = "../runtime" }
bitcoin = { path = "../bitcoin", features = ["cli"] }
thiserror = "1.0"
jsonrpc-http-server = "16.0.0"
jsonrpsee = "0.1.0"
parity-scale-codec = "1.3.6"
serde_json = "1.0.57"
serde = "1.0.116"
futures = "0.3.5"
hex = "0.4.2"
kv = { version = "0.22.0", features = ["json-value"] }
pin-project-lite = "0.2.4"

# Substrate dependencies
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

[dev-dependencies]
substrate-subxt-client = { git = "https://github.com/interlay/substrate-subxt", rev = "c7168df" }
tempdir = "0.3.7"
btc-parachain = { git = "https://gitlab.com/interlay/btc-parachain", branch = "dev", version = "0.5.0", features = ["standalone"] }
btc-parachain-service = { git = "https://gitlab.com/interlay/btc-parachain", branch = "dev", version = "0.5.0", features = ["standalone"] }

