name: Continuous integration

permissions:
  contents: read

on: [pull_request, push]

jobs:
  test:
    name: Test Suite
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Install System Dependencies
        run: |
            sudo apt-get update && sudo apt-get install -y \
            cmake pkg-config libssl-dev git clang curl libc6-dev
      - name: Set variables
        run: |
            echo "TOOLCHAIN=$(rustup show active-toolchain | cut -d " " -f1)" >> $GITHUB_ENV
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.TOOLCHAIN }}
          override: true
          components: rustfmt
      - name: fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - run: rustup component add clippy
      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --release --workspace
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --release --workspace
      - name: test
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: info,regalloc=warn
        with:
          command: test
          args: --release --workspace
      - name: upload artifacts - vault
        uses: actions/upload-artifact@v2
        with:
          name: vault-${{ github.sha }}
          path: target/release/vault
          retention-days: 10
      - name: upload artifacts - oracle
        uses: actions/upload-artifact@v2
        with:
          name: oracle-${{ github.sha }}
          path: target/release/oracle
          retention-days: 10
      - name: upload artifacts - faucet
        uses: actions/upload-artifact@v2
        with:
          name: faucet-${{ github.sha }}
          path: target/release/faucet
          retention-days: 10
